name: first-exercise-workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shell-cmd-job:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Check Python Version
        run: python --version
      - name: Check pip Version
        run: pip --version