name: first-exercise-workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shell-cmd-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello
        run: echo "Hello World"
      - name: multiple line cmd
        run: |
          node -v
          npm -v
      - name: check Python and pip versions
        run: |
          python --version
          pip --version